name: proof
on:
  workflow_dispatch:
  push:
    paths:
      - 'proofs/**'
      - '.github/workflows/ci-proof.yml'
jobs:
  grid-cert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pandas numpy
      - name: Generate claim capsule
        run: |
          python proofs/gen_grid_cert.py --out proofs/GridCert.lean --json proofs/grid.json --claim "Sharpe>=1.0" --sha out/metrics.sha256 || true
      - name: Simulate Lean build (placeholder)
        run: |
          # If you wire Lean later, replace this block with `lake build` and grep "sorry"
          test -s proofs/GridCert.lean || (echo "Missing GridCert.lean" && exit 1)
          echo "OK: placeholder proof build passed"
      - name: Upload proof artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proof-capsule
          path: |
            proofs/GridCert.lean
            proofs/grid.json
            out/metrics.sha256
          if-no-files-found: error
