name: ci-ui

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ui:
    name: UI / ui / test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      # Point the UI at the local mock server during CI
      VITE_API_URL: http://127.0.0.1:8787
      VITE_WS_URL:  ws://127.0.0.1:8787

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ui/package-lock.json

      # --- Minimal, self-contained WS mock for CI ---
      - name: Start mock WS (background)
        env:
          MOCK_WS_PORT: 8787
        run: |
          # Use a throwaway workspace; don't touch repo files
          mkdir -p /tmp/mock-ws && cd /tmp/mock-ws
          npm init -y >/dev/null 2>&1 || true
          npm i --no-save ws@8 >/dev/null
          node - <<'JS' &
          const WebSocket = require('ws');
          const port = parseInt(process.env.MOCK_WS_PORT || '8787', 10);
          const wss = new WebSocket.Server({ host: '127.0.0.1', port });
          wss.on('connection', ws => {
            ws.on('message', m => ws.send(m.toString()));
            ws.send('ready');
          });
          console.log('[mock-ws] listening on ws://127.0.0.1:' + port);
          setInterval(() => {}, 1 << 30);
          JS

      # --- UI build + preview ----------------------------------------------
      - name: Install UI deps
        working-directory: ui
        run: npm ci

      - name: Build UI
        working-directory: ui
        run: npm run build

      - name: Preview UI (background)
        env:
          VITE_API_URL: http://127.0.0.1:8787
          VITE_WS_URL:  ws://127.0.0.1:8787
        working-directory: ui
        run: |
          npm run preview -- --host 127.0.0.1 --port 4173 &

      - name: Wait for services
        env:
          MOCK_WS_PORT: 8787
        run: |
          npx --yes wait-on@7 \
            http://127.0.0.1:4173 \
            ws://127.0.0.1:${MOCK_WS_PORT} \
            --timeout 120000

      - name: Curl landing page (smoke)
        run: |
          curl -fsS http://127.0.0.1:4173 >/dev/null

      # --- Playwright smoke -------------------------------------------------
      - name: Install Playwright (browsers + deps)
        run: npx playwright install --with-deps

      - name: Run Playwright smoke tests
        working-directory: ui
        run: |
          npx playwright test --reporter=list

      # --- Optional: Lighthouse sanity (non-blocking) -----------------------
      - name: Lighthouse (informational)
        if: always()
        run: |
          npm i -g @lhci/cli@0.13.x
          # Don’t fail the job on Lighthouse; we only print a score summary
          lhci healthcheck --assert.off --collect.url=http://127.0.0.1:4173 || true
