name: ci-ui

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ui:
    name: UI / ui / test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      # Point the UI at the local mock server during CI
      VITE_API_URL: http://127.0.0.1:8787
      VITE_WS_URL:  ws://127.0.0.1:8787

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root tools (wait-on, concurrently)
        run: |
          npm i -g wait-on concurrently

      # --- Mock server ------------------------------------------------------
      - name: Install mock-server deps
        working-directory: tools/mock-server
        run: npm ci

      - name: Start mock server (background)
        working-directory: tools/mock-server
        run: |
          npm start &

      # --- UI build + preview ----------------------------------------------
      - name: Install UI deps
        working-directory: ui
        run: npm ci

      - name: Build UI
        working-directory: ui
        run: npm run build

      - name: Preview UI (background)
        working-directory: ui
        run: |
          # Vite preview defaults to 4173; keep it explicit
          npm run preview -- --port 4173 --host 127.0.0.1 &

      - name: Wait for services
        run: |
          # Wait for both the HTTP UI and WS mock endpoints
          wait-on http://127.0.0.1:4173
          # wait-on supports ws:// targets too
          wait-on ws://127.0.0.1:8787

      # --- Playwright smoke -------------------------------------------------
      - name: Install Playwright (browsers + deps)
        run: npx playwright install --with-deps

      - name: Run Playwright smoke tests
        working-directory: ui
        run: |
          npx playwright test --reporter=list

      # --- Optional: Lighthouse sanity (non-blocking) -----------------------
      - name: Lighthouse (informational)
        if: always()
        run: |
          npm i -g @lhci/cli@0.13.x
          # Don’t fail the job on Lighthouse; we only print a score summary
          lhci healthcheck --assert.off --collect.url=http://127.0.0.1:4173 || true
