name: CI
on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install pandas numpy matplotlib pytest
      - name: Validate CSV placeholders
        run: python data/fetch_data.py
      - run: pytest -q
      - name: Walk-forward smoke (deterministic)
        run: |
          python -m backtest.cli wf \
            --csv data/sample_multi_asset_data.csv \
            --strategy sma_cross \
            --params '{"fast":10,"slow":30}' \
            --train-years 0.05 --test-months 0.5 --step-months 0.5 \
            --seed 42 \
            --out-json wf_ci.json
          test -f wf_ci.json
          python - <<'PY'
          import json
          report = json.load(open('wf_ci.json'))
          assert report['fold_count'] > 0, 'walk-forward produced no folds'
          print('wf aggregate:', report['aggregate'])
          PY
