name: docs-diagrams
on:
  push:
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install Playwright and its system deps for Chromium (one and done)
      - name: Install Playwright + deps
        run: |
          npm -g i playwright@1.47.2
          npx playwright install --with-deps chromium

      - name: Render Mermaid blocks from docs/system_diagram.md
        run: |
          NODE_PATH=$(npm root -g) node docs-diagrams/render.mjs docs/system_diagram.md

      - name: Upload diagram artifacts
        uses: actions/upload-artifact@v4
        with:
          name: system-diagram
          path: docs-diagrams/out/*.png
