name: Proof Capsules

on:
  workflow_dispatch:
    inputs:
      results_csv:
        description: 'Path to results CSV (e.g., data/walkforward.csv)'
        required: true
      sharpe_min:
        description: 'Sharpe threshold'
        required: true
        default: '1.0'
      maxdd_max:
        description: 'Max drawdown cap (negative number, e.g., -0.20)'
        required: true
        default: '-0.20'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install pandas numpy
      - name: Generate capsule
        run: |
          python -m proofs.capsule --results "${{ github.event.inputs.results_csv }}" \
                                   --sharpe "${{ github.event.inputs.sharpe_min }}" \
                                   --maxdd "${{ github.event.inputs.maxdd_max }}" \
                                   --out proofs/capsule
      - name: Upload capsule
        uses: actions/upload-artifact@v4
        with:
          name: proof-capsule
          path: proofs/capsule.*
