name: release
on:
  push:
    tags: ['v*.*.*']
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install -U pip && pip install pandas numpy matplotlib
      - name: Build UI
        uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: cd ui && npm ci || npm i && npm run build
      - name: Package artifacts
        run: |
          mkdir -p release
          cp -r ui/dist release/ui_dist || true
          [ -d out ] && cp -r out release/out || true
          tar -czf release.tar.gz release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.tar.gz
