name: UI / ui
on:
  push: { branches: [ main, master ] }
  pull_request: {}
defaults:
  run:
    working-directory: ui
jobs:
  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20 (no cache if no lockfile)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (auto–detect PM)
        shell: bash
        run: |
          if [ ! -d "." ]; then echo "ui/ directory missing"; exit 1; fi
          if [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm i --frozen-lockfile
          elif [ -f yarn.lock ]; then
            corepack enable
            yarn install --frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          else
            echo "No lockfile found; using npm install (no cache)." >&2
            npm install
          fi

      - name: Typecheck & Lint (best-effort)
        run: |
          npm run typecheck --if-present || true
          npm run lint --if-present      || true

      - name: Unit tests
        run: npm test --if-present -- --run

      - name: Build
        run: npm run build --if-present

      - name: Upload UI build
        uses: actions/upload-artifact@v4
        with:
          name: ui-dist
          path: ui/dist
          if-no-files-found: ignore
